server.port=8080
spring.application.name= authentication
spring.datasource.url= jdbc:mysql://localhost:3306/db_projects?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username= root
spring.datasource.password= Momo1982

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto= update

authentication.app.jwtCookieName: nlh-test
authentication.app.jwtSecret: ======================BezKoder=Spring===========================
authentication.app.jwtExpirationMs: 30000
#8640000

spring.security.user.name=jlopez
spring.security.user.password=federer1

file.path=/Users/jaimelopez/Documents/Developer/freelance/mauro-nlh/files