-- MySQL Script generated by MySQL Workbench
-- Mon Dec  26 07:04:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_projects
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_projects` ;

-- -----------------------------------------------------
-- Schema db_projects
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projects` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_projects` ;

-- -----------------------------------------------------
-- Table `db_projects`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`users` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `username` ON `db_projects`.`users` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `email` ON `db_projects`.`users` (`email` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`access_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`access_tokens` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`access_tokens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `token` VARCHAR(255) NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `access_tokens_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_projects`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `token` ON `db_projects`.`access_tokens` (`token` ASC) VISIBLE;

CREATE INDEX `user_id` ON `db_projects`.`access_tokens` (`user_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`projects` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`projects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `location` TEXT NULL DEFAULT NULL,
  `enable` BOOLEAN DEFAULT TRUE,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `db_projects`.`budgets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`budgets` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`budgets` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `document_id`BIGINT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `budgets_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE,
    CONSTRAINT `budgets_ibfk_2`
    FOREIGN KEY (`document_id`)
    REFERENCES `db_projects`.`document` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`budgets` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`documentation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`document` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`document` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` MEDIUMBLOB NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `documente_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`document` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`roles` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`roles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `name` ON `db_projects`.`roles` (`name` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_assignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_assignments` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_assignments` (
  `user_id` BIGINT NOT NULL,
  `project_id` BIGINT NOT NULL,
  `role_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  CONSTRAINT `project_assignments_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_projects`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `project_assignments_ibfk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `project_assignments_ibfk_3`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_projects`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_assignments` (`project_id` ASC) VISIBLE;

CREATE INDEX `role_id` ON `db_projects`.`project_assignments` (`role_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_details` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_details` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NULL DEFAULT NULL,
  `type` VARCHAR(255) NOT NULL,
  `quantity` BIGINT NOT NULL,
  `flats` BIGINT NULL DEFAULT NULL,
  `raw_material` VARCHAR(255) NULL DEFAULT NULL,
  `surface` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_details_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_details` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_detail_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_detail_areas` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_detail_areas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_details_id` BIGINT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_detail_areas_ibfk_1`
    FOREIGN KEY (`project_details_id`)
    REFERENCES `db_projects`.`project_details` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_detail_areas` (`project_details_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_extra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_extra` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_extra` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `additional` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_extra_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_extra` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_general`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_general` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_general` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_general_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_general` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_type_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_type_staff` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_type_staff` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_type_staff` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_projects`.`project_officer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_officer` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_officer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `contact` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_officer_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_officer` (`project_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_projects`.`project_officer_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_officer_staff` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_officer_staff` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_officer_id` BIGINT NOT NULL,
  `type_staff_id` BIGINT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_officer_staff_ibfk_1`
    FOREIGN KEY (`project_officer_id`)
    REFERENCES `db_projects`.`project_officer` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `project_officer_staff_ibfk_2`
    FOREIGN KEY (`type_staff_id`)
    REFERENCES `db_projects`.`project_type_staff` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_officer_staff` (`project_officer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_projects`.`project_schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_schedule` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_schedule` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL ,
  `publish` DATE NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_schedule_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_schedule` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`project_deadline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`project_deadline` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`project_deadline` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL,
  `proposal` DATE NOT NULL,
  `ask` DATE NULL DEFAULT NULL,
  `reply` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `project_deadline_ibfk_1`
    FOREIGN KEY (`project_id`)
    REFERENCES `db_projects`.`projects` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `project_id` ON `db_projects`.`project_deadline` (`project_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `db_projects`.`user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_projects`.`user_roles` ;

CREATE TABLE IF NOT EXISTS `db_projects`.`user_roles` (
  `user_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  CONSTRAINT `user_roles_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_projects`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_roles_ibfk_2`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_projects`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `role_id` ON `db_projects`.`user_roles` (`role_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
